"""Protocol surfaces for state-driven runtime helper modules."""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from typing import Any, Protocol

import pandas as pd


class RuntimeBootstrapState(Protocol):
    BAT_DATA: Any
    PIT_DATA: Any
    META: dict[str, Any]
    PLAYER_KEY_COL: str
    PLAYER_ENTITY_KEY_COL: str
    POSITION_TOKEN_SPLIT_RE: Any
    POSITION_DISPLAY_ORDER: tuple[str, ...]
    PROJECTION_TEXT_SORT_COLS: set[str]
    ALL_TAB_HITTER_STAT_COLS: tuple[str, ...]
    ALL_TAB_PITCH_STAT_COLS: tuple[str, ...]
    PROJECTION_QUERY_CACHE_MAXSIZE: int
    PROJECTION_DYNASTY_HELPERS: Any
    PROJECTION_RATE_LIMITS: Any
    PROJECTION_SERVICE: Any
    _run_calculate_request: Any

    def _refresh_data_if_needed(self) -> None: ...

    def _normalize_player_key(self, value: object) -> str: ...

    def _coerce_meta_years(self, meta: dict[str, Any] | None) -> list[int]: ...

    def _tabular_export_response(self, *args: Any, **kwargs: Any) -> Any: ...

    def _calculator_overlay_values_for_job(self, job_id: str | None) -> dict[str, dict[str, Any]]: ...

    def _calculator_service_from_globals(self) -> Any: ...

    def _enforce_rate_limit(self, *args: Any, **kwargs: Any) -> None: ...

    def filter_records(self, *args: Any, **kwargs: Any) -> Any: ...


class RuntimeOrchestrationState(Protocol):
    META: dict[str, Any]
    BAT_DATA: Any
    PIT_DATA: Any
    PROJECTION_FRESHNESS: dict[str, Any]
    APP_ENVIRONMENT: str
    CORS_ALLOW_ORIGINS: list[str]
    TRUST_X_FORWARDED_FOR: bool
    TRUSTED_PROXY_NETWORKS: tuple[Any, ...] | list[Any]
    CANONICAL_HOST: str
    REQUIRE_CALCULATE_AUTH: bool
    CALCULATE_API_KEY_IDENTITIES: dict[str, str]
    CALCULATOR_PREWARM_LOCK: Any
    CALCULATOR_PREWARM_STATE: dict[str, Any]
    API_NO_CACHE_HEADERS: dict[str, str]
    APP_BUILD_ID: str
    DEPLOY_COMMIT_SHA: str
    APP_BUILD_AT: str | None
    REQUIRE_PRECOMPUTED_DYNASTY_LOOKUP: bool
    INDEX_PATH: Any
    CALCULATOR_JOB_LOCK: Any
    CALCULATOR_JOBS: dict[str, dict[str, Any]]
    CALC_JOB_CANCELLED_STATUS: str
    CALC_RESULT_CACHE_LOCK: Any
    CALC_RESULT_CACHE: dict[str, Any]
    CALCULATOR_SYNC_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_SYNC_AUTH_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_CREATE_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_CREATE_AUTH_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_STATUS_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_STATUS_AUTH_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_REQUEST_TIMEOUT_SECONDS: int
    PROJECTION_RATE_LIMITS: Any
    REDIS_URL: str
    CALCULATOR_JOB_EXECUTOR: ThreadPoolExecutor
    CALCULATOR_MAX_ACTIVE_JOBS_PER_IP: int
    CALCULATOR_MAX_ACTIVE_JOBS_TOTAL: int
    EXPORT_INTERNAL_COLUMN_BLOCKLIST: set[str]
    CALC_LOGGER: Any
    CalculateRequest: Any

    def _refresh_data_if_needed(self) -> None: ...

    def _calculator_guardrails_payload(self) -> dict[str, Any]: ...

    def _current_data_version(self) -> str: ...

    def _inspect_precomputed_default_dynasty_lookup(self) -> Any: ...

    def _cleanup_calculation_jobs(self, now_ts: float | None = None) -> None: ...

    def _cleanup_local_result_cache(self, now_ts: float | None = None) -> None: ...

    def _rate_limit_bucket_count(self) -> int: ...

    def _rate_limit_activity_snapshot(self) -> dict[str, Any]: ...

    def _iso_now(self) -> str: ...

    def _enforce_rate_limit(self, *args: Any, **kwargs: Any) -> None: ...

    def _flatten_explanations_for_export(self, explanations: dict[str, dict[str, Any]]) -> list[dict[str, Any]]: ...

    def _tabular_export_response(self, *args: Any, **kwargs: Any) -> Any: ...

    def _default_calculator_export_columns(self, rows: list[dict[str, Any]]) -> list[str]: ...

    def _calc_result_cache_key(self, settings: dict[str, Any]) -> str: ...

    def _result_cache_get(self, key: str) -> dict[str, Any] | None: ...

    def _client_ip(self, request: Any | None) -> str: ...

    def _active_jobs_for_ip(self, client_ip: str) -> int: ...

    def _cache_calculation_job_snapshot(self, job: dict[str, Any]) -> None: ...

    def _cached_calculation_job_snapshot(self, job_id: str) -> dict[str, Any] | None: ...

    def _calculation_job_public_payload(self, job: dict[str, Any]) -> dict[str, Any]: ...

    def _mark_job_cancelled_locked(self, job: dict[str, Any], *, now: str | None = None) -> None: ...

    def _track_active_job(self, job_id: str, client_ip: str) -> None: ...

    def _untrack_active_job(self, job_id: str, client_ip: str | None = None) -> None: ...

    def _set_job_cancel_requested(self, job_id: str) -> None: ...

    def _clear_job_cancel_requested(self, job_id: str) -> None: ...

    def _job_cancel_requested(self, job_id: str) -> bool: ...


class RuntimeStateHelpersState(Protocol):
    os: Any
    time: Any
    APP_ENVIRONMENT: str
    CORS_ALLOW_ORIGINS: list[str]
    TRUST_X_FORWARDED_FOR: bool
    TRUSTED_PROXY_NETWORKS: list[Any] | tuple[Any, ...]
    REQUIRE_CALCULATE_AUTH: bool
    CALCULATE_API_KEY_IDENTITIES: dict[str, str]
    DYNASTY_LOOKUP_CACHE_PATH: Any
    DynastyLookupCacheInspection: Any
    CALC_LOGGER: Any
    EXCEL_PATH: Any
    ROTO_HITTER_CATEGORY_FIELDS: tuple[str, ...]
    ROTO_PITCHER_CATEGORY_FIELDS: tuple[str, ...]
    PointsCalculatorContext: Any
    BAT_DATA: Any
    PIT_DATA: Any
    BAT_DATA_RAW: Any
    PIT_DATA_RAW: Any
    META: dict[str, Any]
    PLAYER_KEY_COL: str
    PLAYER_ENTITY_KEY_COL: str
    CALCULATOR_PREWARM_LOCK: Any
    CALCULATOR_PREWARM_STATE: dict[str, Any]
    PREWARM_CONFIG_COUNT: int
    DEFAULT_POINTS_SCORING: dict[str, float]
    CALCULATOR_JOB_LOCK: Any
    CALCULATOR_JOBS: dict[str, dict[str, Any]]
    CALCULATOR_JOB_EXECUTOR: Any
    CALC_JOB_CANCELLED_STATUS: str
    CALCULATOR_SYNC_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_SYNC_AUTH_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_CREATE_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_CREATE_AUTH_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_STATUS_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_JOB_STATUS_AUTH_RATE_LIMIT_PER_MINUTE: int
    CALCULATOR_MAX_ACTIVE_JOBS_PER_IP: int
    CALCULATOR_MAX_ACTIVE_JOBS_TOTAL: int
    REQUIRE_PRECOMPUTED_DYNASTY_LOOKUP: bool

    def _current_data_version(self) -> str: ...

    def _value_col_sort_key(self, col: str) -> tuple[int, int | str]: ...

    def core_inspect_precomputed_default_dynasty_lookup(self, **kwargs: Any) -> Any: ...

    def _inspect_precomputed_default_dynasty_lookup(self) -> Any: ...

    def core_calculate_common_dynasty_frame(self, **kwargs: Any) -> pd.DataFrame: ...

    def core_calculate_league_dynasty_frame(self, **kwargs: Any) -> pd.DataFrame: ...

    def core_calculate_points_dynasty_frame(self, **kwargs: Any) -> pd.DataFrame: ...

    def _ensure_backend_module_path(self) -> None: ...

    def _coerce_bool(self, value: object, *, default: bool = False) -> bool: ...

    def _average_recent_projection_rows(self, rows: Any, *, is_hitter: bool) -> Any: ...

    def _coerce_meta_years(self, meta: dict[str, Any] | None) -> list[int]: ...

    def _valuation_years(self, start_year: int, horizon: int, valid_years: list[int]) -> list[int]: ...

    def _coerce_record_year(self, value: object) -> int | None: ...

    def _points_player_identity(self, row: dict[str, Any]) -> str: ...

    def _normalize_player_key(self, value: object) -> str: ...

    def _row_team_value(self, row: dict[str, Any]) -> str: ...

    def _merge_position_value(self, hit_pos: object, pit_pos: object) -> str | None: ...

    def _coerce_minor_eligible(self, value: object) -> bool: ...

    def _calculate_hitter_points_breakdown(self, row: dict[str, Any] | None, scoring: dict[str, float]) -> dict[str, Any]: ...

    def _calculate_pitcher_points_breakdown(self, row: dict[str, Any] | None, scoring: dict[str, float]) -> dict[str, Any]: ...

    def _stat_or_zero(self, row: dict[str, Any] | None, key: str) -> float: ...

    def _points_hitter_eligible_slots(self, pos_value: object) -> set[str]: ...

    def _points_pitcher_eligible_slots(self, pos_value: object) -> set[str]: ...

    def _points_slot_replacement(self, entries: list[dict[str, object]], **kwargs: Any) -> dict[str, float]: ...

    def _iso_now(self) -> str: ...

    def _refresh_data_if_needed(self) -> None: ...

    def _default_calculation_cache_params(self) -> dict[str, Any]: ...

    def _calculate_common_dynasty_frame_cached(self, **kwargs: Any) -> pd.DataFrame: ...

    def _calculate_league_dynasty_frame_cached(self, **kwargs: Any) -> pd.DataFrame: ...

    def _calculate_points_dynasty_frame_cached(self, **kwargs: Any) -> pd.DataFrame: ...

    def _roto_category_settings_from_dict(self, source: dict[str, Any] | None) -> dict[str, bool]: ...

    def _get_default_dynasty_lookup(self) -> tuple[dict[str, dict], dict[str, dict], set[str], list[str]]: ...

    def _cached_calculation_job_snapshot(self, job_id: str) -> dict[str, Any] | None: ...

    def build_calculator_service(self, **kwargs: Any) -> Any: ...

    def _calc_result_cache_key(self, settings: dict[str, Any]) -> str: ...

    def _result_cache_get(self, key: str) -> dict[str, Any] | None: ...

    def _result_cache_set(self, key: str, payload: dict[str, Any]) -> None: ...

    def _is_user_fixable_calculation_error(self, message: str) -> bool: ...

    def _player_identity_by_name(self) -> dict[str, tuple[str, str | None]]: ...

    def _selected_roto_categories(self, settings: dict[str, Any]) -> tuple[list[str], list[str]]: ...

    def _start_year_roto_stats_by_entity(self, *, start_year: int) -> dict[str, dict[str, float]]: ...

    def _projection_identity_key(self, row: dict[str, Any] | pd.Series) -> str: ...

    def _build_calculation_explanations(self, out: pd.DataFrame, *, settings: dict[str, Any]) -> dict[str, dict[str, Any]]: ...

    def _clean_records_for_json(self, records: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

    def _flatten_explanations_for_export(self, explanations: dict[str, dict[str, Any]]) -> list[dict[str, Any]]: ...

    def _tabular_export_response(self, *args: Any, **kwargs: Any) -> Any: ...

    def _enforce_rate_limit(self, *args: Any, **kwargs: Any) -> None: ...

    def _client_ip(self, request: Any | None) -> str: ...

    def _active_jobs_for_ip(self, client_ip: str) -> int: ...

    def _cleanup_calculation_jobs(self, now_ts: float | None = None) -> None: ...

    def _cache_calculation_job_snapshot(self, job: dict[str, Any]) -> None: ...

    def _calculation_job_public_payload(self, job: dict[str, Any]) -> dict[str, Any]: ...

    def _mark_job_cancelled_locked(self, job: dict[str, Any], *, now: str | None = None) -> None: ...
