from __future__ import annotations

from typing import Any, Callable

from backend.core.calculator_orchestration import CalculatorOrchestrationContext
from backend.core.status_orchestration import StatusOrchestrationContext
from backend.services.calculator import CalculatorService, CalculatorServiceContext


def build_status_orchestration_context(
    *,
    refresh_data_if_needed: Callable[[], None],
    meta_getter: Callable[[], dict[str, Any]],
    calculator_guardrails_payload: Callable[[], dict[str, Any]],
    projection_freshness_getter: Callable[[], dict[str, Any]],
    environment: str,
    cors_allow_origins: tuple[str, ...],
    trust_x_forwarded_for: bool,
    trusted_proxy_cidrs: tuple[str, ...],
    canonical_host: str,
    require_calculate_auth: bool,
    calculate_api_keys_configured: bool,
    calculator_prewarm_lock: Any,
    calculator_prewarm_state: dict[str, Any],
    api_no_cache_headers: dict[str, str],
    current_data_version: Callable[[], str],
    app_build_id: str,
    deploy_commit_sha: str,
    app_build_at: str | None,
    inspect_precomputed_default_dynasty_lookup: Callable[[], Any],
    require_precomputed_dynasty_lookup: bool,
    index_path: Any,
    calculator_job_lock: Any,
    cleanup_calculation_jobs: Callable[[float | None], None],
    calculator_jobs: dict[str, dict],
    calc_job_cancelled_status: str,
    calc_result_cache_lock: Any,
    cleanup_local_result_cache: Callable[[float | None], None],
    calc_result_cache: dict[str, tuple[float, dict]],
    rate_limit_bucket_count_getter: Callable[[], int],
    rate_limit_activity_snapshot_getter: Callable[[], dict[str, Any]],
    calculator_sync_rate_limit_per_minute: int,
    calculator_sync_auth_rate_limit_per_minute: int,
    calculator_job_create_rate_limit_per_minute: int,
    calculator_job_create_auth_rate_limit_per_minute: int,
    calculator_job_status_rate_limit_per_minute: int,
    calculator_job_status_auth_rate_limit_per_minute: int,
    calculator_request_timeout_seconds: int,
    calculator_max_active_jobs_per_ip: int,
    calculator_max_active_jobs_total: int,
    projection_rate_limit_per_minute: int,
    projection_export_rate_limit_per_minute: int,
    redis_url: str,
    redis_client_getter: Callable[[], Any] | None,
    bat_data_getter: Callable[[], list[dict]],
    pit_data_getter: Callable[[], list[dict]],
    calculator_worker_available: Callable[[], bool],
    iso_now: Callable[[], str],
) -> StatusOrchestrationContext:
    return StatusOrchestrationContext(
        refresh_data_if_needed=refresh_data_if_needed,
        meta_getter=meta_getter,
        calculator_guardrails_payload=calculator_guardrails_payload,
        projection_freshness_getter=projection_freshness_getter,
        environment=environment,
        cors_allow_origins=cors_allow_origins,
        trust_x_forwarded_for=trust_x_forwarded_for,
        trusted_proxy_cidrs=trusted_proxy_cidrs,
        canonical_host=canonical_host,
        require_calculate_auth=require_calculate_auth,
        calculate_api_keys_configured=calculate_api_keys_configured,
        calculator_prewarm_lock=calculator_prewarm_lock,
        calculator_prewarm_state=calculator_prewarm_state,
        api_no_cache_headers=api_no_cache_headers,
        current_data_version=current_data_version,
        app_build_id=app_build_id,
        deploy_commit_sha=deploy_commit_sha,
        app_build_at=app_build_at,
        inspect_precomputed_default_dynasty_lookup=inspect_precomputed_default_dynasty_lookup,
        require_precomputed_dynasty_lookup=require_precomputed_dynasty_lookup,
        index_path=index_path,
        calculator_job_lock=calculator_job_lock,
        cleanup_calculation_jobs=cleanup_calculation_jobs,
        calculator_jobs=calculator_jobs,
        calc_job_cancelled_status=calc_job_cancelled_status,
        calc_result_cache_lock=calc_result_cache_lock,
        cleanup_local_result_cache=cleanup_local_result_cache,
        calc_result_cache=calc_result_cache,
        rate_limit_bucket_count_getter=rate_limit_bucket_count_getter,
        rate_limit_activity_snapshot_getter=rate_limit_activity_snapshot_getter,
        calculator_sync_rate_limit_per_minute=calculator_sync_rate_limit_per_minute,
        calculator_sync_auth_rate_limit_per_minute=calculator_sync_auth_rate_limit_per_minute,
        calculator_job_create_rate_limit_per_minute=calculator_job_create_rate_limit_per_minute,
        calculator_job_create_auth_rate_limit_per_minute=calculator_job_create_auth_rate_limit_per_minute,
        calculator_job_status_rate_limit_per_minute=calculator_job_status_rate_limit_per_minute,
        calculator_job_status_auth_rate_limit_per_minute=calculator_job_status_auth_rate_limit_per_minute,
        calculator_request_timeout_seconds=calculator_request_timeout_seconds,
        calculator_max_active_jobs_per_ip=calculator_max_active_jobs_per_ip,
        calculator_max_active_jobs_total=calculator_max_active_jobs_total,
        projection_rate_limit_per_minute=projection_rate_limit_per_minute,
        projection_export_rate_limit_per_minute=projection_export_rate_limit_per_minute,
        redis_url=redis_url,
        redis_client_getter=redis_client_getter,
        bat_data_getter=bat_data_getter,
        pit_data_getter=pit_data_getter,
        calculator_worker_available=calculator_worker_available,
        iso_now=iso_now,
    )


def build_calculator_orchestration_context(
    *,
    calculate_request_model: type,
    enforce_rate_limit: Callable[..., None],
    sync_rate_limit_per_minute: int,
    sync_auth_rate_limit_per_minute: int,
    job_create_rate_limit_per_minute: int,
    job_create_auth_rate_limit_per_minute: int,
    job_status_rate_limit_per_minute: int,
    job_status_auth_rate_limit_per_minute: int,
    flatten_explanations_for_export: Callable[[dict[str, Any]], list[dict]],
    tabular_export_response: Callable[..., Any],
    default_calculator_export_columns: Callable[[list[dict]], list[str]],
    export_internal_column_blocklist: set[str],
    calc_result_cache_key: Callable[[dict[str, Any]], str],
    result_cache_get: Callable[[str], dict | None],
    client_ip: Callable[[Any], str],
    iso_now: Callable[[], str],
    active_jobs_for_ip: Callable[[str], int],
    calculator_max_active_jobs_per_ip: int,
    calculator_max_active_jobs_total: int,
    calculator_job_lock: Any,
    calculator_jobs: dict[str, dict],
    cleanup_calculation_jobs: Callable[[float | None], None],
    cache_calculation_job_snapshot: Callable[[dict], None],
    cached_calculation_job_snapshot: Callable[[str], dict | None],
    calculation_job_public_payload: Callable[[dict], dict],
    mark_job_cancelled_locked: Callable[[dict], None],
    calculator_job_executor: Any,
    calc_job_cancelled_status: str,
    calc_logger: Any,
    track_active_job: Callable[[str, str], None],
    untrack_active_job: Callable[[str, str | None], None],
    set_job_cancel_requested: Callable[[str], None],
    clear_job_cancel_requested: Callable[[str], None],
    job_cancel_requested: Callable[[str], bool],
) -> CalculatorOrchestrationContext:
    return CalculatorOrchestrationContext(
        calculate_request_model=calculate_request_model,
        enforce_rate_limit=enforce_rate_limit,
        sync_rate_limit_per_minute=sync_rate_limit_per_minute,
        sync_auth_rate_limit_per_minute=sync_auth_rate_limit_per_minute,
        job_create_rate_limit_per_minute=job_create_rate_limit_per_minute,
        job_create_auth_rate_limit_per_minute=job_create_auth_rate_limit_per_minute,
        job_status_rate_limit_per_minute=job_status_rate_limit_per_minute,
        job_status_auth_rate_limit_per_minute=job_status_auth_rate_limit_per_minute,
        flatten_explanations_for_export=flatten_explanations_for_export,
        tabular_export_response=tabular_export_response,
        default_calculator_export_columns=default_calculator_export_columns,
        export_internal_column_blocklist=export_internal_column_blocklist,
        calc_result_cache_key=calc_result_cache_key,
        result_cache_get=result_cache_get,
        client_ip=client_ip,
        iso_now=iso_now,
        active_jobs_for_ip=active_jobs_for_ip,
        calculator_max_active_jobs_per_ip=calculator_max_active_jobs_per_ip,
        calculator_max_active_jobs_total=calculator_max_active_jobs_total,
        calculator_job_lock=calculator_job_lock,
        calculator_jobs=calculator_jobs,
        cleanup_calculation_jobs=cleanup_calculation_jobs,
        cache_calculation_job_snapshot=cache_calculation_job_snapshot,
        cached_calculation_job_snapshot=cached_calculation_job_snapshot,
        calculation_job_public_payload=calculation_job_public_payload,
        mark_job_cancelled_locked=mark_job_cancelled_locked,
        calculator_job_executor=calculator_job_executor,
        calc_job_cancelled_status=calc_job_cancelled_status,
        calc_logger=calc_logger,
        track_active_job=track_active_job,
        untrack_active_job=untrack_active_job,
        set_job_cancel_requested=set_job_cancel_requested,
        clear_job_cancel_requested=clear_job_cancel_requested,
        job_cancel_requested=job_cancel_requested,
    )


def build_calculator_service(
    *,
    refresh_data_if_needed: Callable[..., Any],
    coerce_meta_years: Callable[..., Any],
    get_meta: Callable[..., Any],
    calc_result_cache_key: Callable[..., Any],
    result_cache_get: Callable[..., Any],
    result_cache_set: Callable[..., Any],
    calculate_common_dynasty_frame_cached: Callable[..., Any],
    calculate_points_dynasty_frame_cached: Callable[..., Any],
    roto_category_settings_from_dict: Callable[..., Any],
    is_user_fixable_calculation_error: Callable[..., Any],
    player_identity_by_name: Callable[..., Any],
    normalize_player_key: Callable[..., Any],
    player_key_col: str,
    player_entity_key_col: str,
    selected_roto_categories: Callable[..., Any],
    start_year_roto_stats_by_entity: Callable[..., Any],
    projection_identity_key: Callable[..., Any],
    build_calculation_explanations: Callable[..., Any],
    clean_records_for_json: Callable[..., Any],
    flatten_explanations_for_export: Callable[..., Any],
    tabular_export_response: Callable[..., Any],
    calc_logger: Any,
    enforce_rate_limit: Callable[..., Any],
    sync_rate_limit_per_minute: int,
    sync_auth_rate_limit_per_minute: int,
    job_create_rate_limit_per_minute: int,
    job_create_auth_rate_limit_per_minute: int,
    job_status_rate_limit_per_minute: int,
    job_status_auth_rate_limit_per_minute: int,
    client_ip: Callable[..., Any],
    iso_now: Callable[..., Any],
    active_jobs_for_ip: Callable[..., Any],
    calculator_max_active_jobs_per_ip: int,
    calculator_max_active_jobs_total: int,
    calculator_job_lock: Any,
    calculator_jobs: dict[str, dict],
    cleanup_calculation_jobs: Callable[..., Any],
    cache_calculation_job_snapshot: Callable[..., Any],
    cached_calculation_job_snapshot: Callable[..., Any],
    calculation_job_public_payload: Callable[..., Any],
    mark_job_cancelled_locked: Callable[..., Any],
    calculator_job_executor: Any,
    calc_job_cancelled_status: str,
) -> CalculatorService:
    return CalculatorService(
        CalculatorServiceContext(
            refresh_data_if_needed=refresh_data_if_needed,
            coerce_meta_years=coerce_meta_years,
            get_meta=get_meta,
            calc_result_cache_key=calc_result_cache_key,
            result_cache_get=result_cache_get,
            result_cache_set=result_cache_set,
            calculate_common_dynasty_frame_cached=calculate_common_dynasty_frame_cached,
            calculate_points_dynasty_frame_cached=calculate_points_dynasty_frame_cached,
            roto_category_settings_from_dict=roto_category_settings_from_dict,
            is_user_fixable_calculation_error=is_user_fixable_calculation_error,
            player_identity_by_name=player_identity_by_name,
            normalize_player_key=normalize_player_key,
            player_key_col=player_key_col,
            player_entity_key_col=player_entity_key_col,
            selected_roto_categories=selected_roto_categories,
            start_year_roto_stats_by_entity=start_year_roto_stats_by_entity,
            projection_identity_key=projection_identity_key,
            build_calculation_explanations=build_calculation_explanations,
            clean_records_for_json=clean_records_for_json,
            flatten_explanations_for_export=flatten_explanations_for_export,
            tabular_export_response=tabular_export_response,
            calc_logger=calc_logger,
            enforce_rate_limit=enforce_rate_limit,
            sync_rate_limit_per_minute=sync_rate_limit_per_minute,
            sync_auth_rate_limit_per_minute=sync_auth_rate_limit_per_minute,
            job_create_rate_limit_per_minute=job_create_rate_limit_per_minute,
            job_create_auth_rate_limit_per_minute=job_create_auth_rate_limit_per_minute,
            job_status_rate_limit_per_minute=job_status_rate_limit_per_minute,
            job_status_auth_rate_limit_per_minute=job_status_auth_rate_limit_per_minute,
            client_ip=client_ip,
            iso_now=iso_now,
            active_jobs_for_ip=active_jobs_for_ip,
            calculator_max_active_jobs_per_ip=calculator_max_active_jobs_per_ip,
            calculator_max_active_jobs_total=calculator_max_active_jobs_total,
            calculator_job_lock=calculator_job_lock,
            calculator_jobs=calculator_jobs,
            cleanup_calculation_jobs=cleanup_calculation_jobs,
            cache_calculation_job_snapshot=cache_calculation_job_snapshot,
            cached_calculation_job_snapshot=cached_calculation_job_snapshot,
            calculation_job_public_payload=calculation_job_public_payload,
            mark_job_cancelled_locked=mark_job_cancelled_locked,
            calculator_job_executor=calculator_job_executor,
            calc_job_cancelled_status=calc_job_cancelled_status,
        )
    )
