#!/usr/bin/env python3
"""Fail CI when projection quality report falls below guardrail thresholds."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate projection quality report generated by preprocess.py.",
    )
    parser.add_argument(
        "--report",
        default="tmp/projection_quality_report.json",
        help="Path to projection quality report JSON (default: tmp/projection_quality_report.json).",
    )
    parser.add_argument(
        "--min-date-coverage-pct",
        type=float,
        default=95.0,
        help="Minimum acceptable Date coverage percentage per sheet (default: 95.0).",
    )
    return parser.parse_args()


def _as_number(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if number != number:  # NaN
        return None
    return number


def _as_int(value: Any) -> int | None:
    number = _as_number(value)
    if number is None or not float(number).is_integer():
        return None
    return int(number)


def _sheet_guardrail_violations(
    *,
    label: str,
    payload: dict[str, Any],
    min_date_coverage_pct: float,
) -> list[str]:
    violations: list[str] = []

    invalid_year_values = _as_int(payload.get("invalid_year_values"))
    if invalid_year_values is None:
        violations.append(f"{label}: invalid_year_values is missing or non-integer.")
    elif invalid_year_values > 0:
        violations.append(f"{label}: invalid_year_values={invalid_year_values} (must be 0).")

    blank_player_rows = _as_int(payload.get("blank_player_rows"))
    if blank_player_rows is None:
        violations.append(f"{label}: blank_player_rows is missing or non-integer.")
    elif blank_player_rows > 0:
        violations.append(f"{label}: blank_player_rows={blank_player_rows} (must be 0).")

    blank_team_rows = _as_int(payload.get("blank_team_rows"))
    if blank_team_rows is None:
        violations.append(f"{label}: blank_team_rows is missing or non-integer.")
    elif blank_team_rows > 0:
        violations.append(f"{label}: blank_team_rows={blank_team_rows} (must be 0).")

    date_coverage_pct = _as_number(payload.get("date_coverage_pct"))
    if date_coverage_pct is None:
        violations.append(f"{label}: date_coverage_pct is missing or non-numeric.")
    elif date_coverage_pct < float(min_date_coverage_pct):
        violations.append(
            f"{label}: date_coverage_pct={date_coverage_pct:.1f} (minimum {float(min_date_coverage_pct):.1f})."
        )

    return violations


def validate_projection_quality_report(payload: dict[str, Any], *, min_date_coverage_pct: float) -> list[str]:
    violations: list[str] = []

    bat = payload.get("bat")
    pitch = payload.get("pitch")
    if not isinstance(bat, dict):
        violations.append("bat section is missing or invalid.")
    if not isinstance(pitch, dict):
        violations.append("pitch section is missing or invalid.")

    if isinstance(bat, dict):
        violations.extend(
            _sheet_guardrail_violations(
                label="bat",
                payload=bat,
                min_date_coverage_pct=min_date_coverage_pct,
            )
        )
    if isinstance(pitch, dict):
        violations.extend(
            _sheet_guardrail_violations(
                label="pitch",
                payload=pitch,
                min_date_coverage_pct=min_date_coverage_pct,
            )
        )

    year_sets_match = payload.get("year_sets_match")
    if year_sets_match is not True:
        violations.append("year_sets_match must be true.")

    validation_window = payload.get("validation_window")
    if not isinstance(validation_window, dict):
        violations.append("validation_window is missing or invalid.")
    else:
        expected_years = validation_window.get("expected_years")
        if not isinstance(expected_years, list) or not expected_years:
            violations.append("validation_window.expected_years is missing or empty.")

    return violations


def main() -> int:
    args = _parse_args()
    report_path = Path(args.report).expanduser().resolve()
    if not report_path.exists():
        print(f"Projection quality report not found: {report_path}")
        return 2

    try:
        payload = json.loads(report_path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"Failed to parse projection quality report {report_path}: {exc}")
        return 2

    if not isinstance(payload, dict):
        print(f"Projection quality report is not a JSON object: {report_path}")
        return 2

    violations = validate_projection_quality_report(payload, min_date_coverage_pct=args.min_date_coverage_pct)
    if violations:
        print("Projection quality guardrail failed:")
        for violation in violations:
            print(f" - {violation}")
        return 1

    print(f"Projection quality guardrail passed ({report_path}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
